services:
  rag-app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rag.rule=Host(`rag.horacioai.com`)"
      - "traefik.http.routers.rag.entrypoints=websecure"
      - "traefik.http.routers.rag.tls.certresolver=letsencrypt"
      - "traefik.http.services.rag.loadbalancer.server.port=8080"
    networks:
      - proxy

networks:
  proxy:
    external: true
